spring:
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-i4doar87.sql.tencentcdb.com:25769/english?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Jp15149622693
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088