spring:
  datasource:
    url: jdbc:mysql://localhost/mybatis-plus?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 15149622693
    driver-class-name: com.mysql.cj.jdbc.Driver
